# Installs packages to run edx locally on a single instance
#
---

- set_fact:
    mysql_user_host: "{{ EDXAPP_MYSQL_HOST }}"

- set_fact:
    mysql_user_host: '%'
  when: EDXAPP_MYSQL_HOST != 'localhost'
  
  
- name: Install packages needed for single server
  apt:
    name: "{{ item }}"
    install_recommends: yes
    state: present
  with_items: "{{ edxlocal_debian_pkgs }}"

# TODO: Add a test to make sure mysql is running.

- name: create databases
  mysql_db:
    db: "{{ item }}"
    login_user: "{{ EDXAPP_MYSQL_USER_ADMIN.split('@')[0] }}@{{ EDXAPP_MYSQL_CLOUD_SERVER_NAME }}"
    login_password: "{{ EDXAPP_MYSQL_PASSWORD_ADMIN }}"
    login_host: "{{ MYSQL_SERVER_FQDN }}"
    ssl_ca: "{{ AZURE_MYSQL_SSL_CA }}"
    state: present
    encoding: utf8
  when: item != None and item != ''
  with_items: "{{ edxlocal_databases }}"

- name: create database users
  mysql_user:
    host: "{{ mysql_user_host }}"
    login_user: "{{ EDXAPP_MYSQL_USER_ADMIN.split('@')[0] }}@{{ EDXAPP_MYSQL_CLOUD_SERVER_NAME }}"
    login_password: "{{ EDXAPP_MYSQL_PASSWORD_ADMIN }}"
    login_host: "{{ MYSQL_SERVER_FQDN }}"
    ssl_ca: "{{ AZURE_MYSQL_SSL_CA }}"	
    name: "{{ item.user.split('@')[0] }}"
    password: "{{ item.pass }}"
    priv: "{{ item.db }}.*:ALL"
    append_privs: yes
  when: item.db != None and item.db != ''
  with_items: "{{ edxlocal_database_users }}"

- name: setup the migration db user
  mysql_user:
    host: "{{ mysql_user_host }}"
    login_user: "{{ EDXAPP_MYSQL_USER_ADMIN.split('@')[0] }}@{{ EDXAPP_MYSQL_CLOUD_SERVER_NAME }}"
    login_password: "{{ EDXAPP_MYSQL_PASSWORD_ADMIN }}"
    login_host: "{{ MYSQL_SERVER_FQDN }}"
    ssl_ca: "{{ AZURE_MYSQL_SSL_CA }}"
    name: "{{ COMMON_MYSQL_MIGRATE_USER.split('@')[0] }}"
    password: "{{ COMMON_MYSQL_MIGRATE_PASS }}"
    priv: "{{ item }}.*:ALL"
    append_privs: yes
  when: item != None and item != ''
  with_items: "{{ edxlocal_databases }}"

- name: create api user for the analytics api
  mysql_user:
    host: "{{ mysql_user_host }}"
    login_user: "{{ EDXAPP_MYSQL_USER_ADMIN.split('@')[0] }}@{{ EDXAPP_MYSQL_CLOUD_SERVER_NAME }}"
    login_password: "{{ EDXAPP_MYSQL_PASSWORD_ADMIN }}"
    login_host: "{{ MYSQL_SERVER_FQDN }}"
    ssl_ca: "{{ AZURE_MYSQL_SSL_CA }}"
    name: "{{ ANALYTICS_API_DATABASES.default.USER.split('@')[0] }}"
    password: "{{ ANALYTICS_API_DATABASES.default.PASSWORD }}"
    priv: '{{ ANALYTICS_API_DATABASES.default.NAME }}.*:ALL/reports.*:SELECT'
  when: ANALYTICS_API_DATABASES.default is defined

- name: create read-only reports user for the analytics-api
  mysql_user:
    host: "{{ mysql_user_host }}"
    login_user: "{{ EDXAPP_MYSQL_USER_ADMIN.split('@')[0] }}@{{ EDXAPP_MYSQL_CLOUD_SERVER_NAME }}"
    login_password: "{{ EDXAPP_MYSQL_PASSWORD_ADMIN }}"
    login_host: "{{ MYSQL_SERVER_FQDN }}"
    ssl_ca: "{{ AZURE_MYSQL_SSL_CA }}"
    name: "{{ ANALYTICS_API_DATABASES.reports.USER.split('@')[0] }}"
    password: "{{ ANALYTICS_API_DATABASES.reports.PASSWORD }}"
    priv: '{{ ANALYTICS_API_DATABASES.reports.NAME }}.*:SELECT'
  when: ANALYTICS_API_DATABASES.reports is defined

- name: create a database for the hive metastore
  mysql_db:
    host: "{{ mysql_user_host }}"
    login_user: "{{ EDXAPP_MYSQL_USER_ADMIN.split('@')[0] }}@{{ EDXAPP_MYSQL_CLOUD_SERVER_NAME }}"
    login_password: "{{ EDXAPP_MYSQL_PASSWORD_ADMIN }}"
    login_host: "{{ MYSQL_SERVER_FQDN }}"
    ssl_ca: "{{ AZURE_MYSQL_SSL_CA }}"
    db: "{{ HIVE_METASTORE_DATABASE.name }}"
    state: "present"
    encoding: "latin1"
  when: HIVE_METASTORE_DATABASE is defined

- name: setup the edx-notes-api db user
  mysql_user:
    host: "{{ mysql_user_host }}"
    login_user: "{{ EDXAPP_MYSQL_USER_ADMIN.split('@')[0] }}@{{ EDXAPP_MYSQL_CLOUD_SERVER_NAME }}"
    login_password: "{{ EDXAPP_MYSQL_PASSWORD_ADMIN }}"
    login_host: "{{ MYSQL_SERVER_FQDN }}"
    ssl_ca: "{{ AZURE_MYSQL_SSL_CA }}"
    name: "{{ EDX_NOTES_API_MYSQL_DB_USER.split('@')[0] }}"
    password: "{{ EDX_NOTES_API_MYSQL_DB_PASS }}"
    priv: "{{ EDX_NOTES_API_MYSQL_DB_NAME }}.*:SELECT,INSERT,UPDATE,DELETE"
  when: EDX_NOTES_API_MYSQL_DB_USER is defined

- name: setup the read-only db user
  mysql_user:
    host: "{{ mysql_user_host }}"
    login_user: "{{ EDXAPP_MYSQL_USER_ADMIN.split('@')[0] }}@{{ EDXAPP_MYSQL_CLOUD_SERVER_NAME }}"
    login_password: "{{ EDXAPP_MYSQL_PASSWORD_ADMIN }}"
    login_host: "{{ MYSQL_SERVER_FQDN }}"
    ssl_ca: "{{ AZURE_MYSQL_SSL_CA }}"
    name: "{{ COMMON_MYSQL_READ_ONLY_USER.split('@')[0] }}"
    password: "{{ COMMON_MYSQL_READ_ONLY_PASS }}"
    priv: "*.*:SELECT"

- name: setup the admin db user
  mysql_user:
    host: "{{ mysql_user_host }}"
    login_user: "{{ EDXAPP_MYSQL_USER_ADMIN.split('@')[0] }}@{{ EDXAPP_MYSQL_CLOUD_SERVER_NAME }}"
    login_password: "{{ EDXAPP_MYSQL_PASSWORD_ADMIN }}"
    login_host: "{{ MYSQL_SERVER_FQDN }}"
    ssl_ca: "{{ AZURE_MYSQL_SSL_CA }}"
    name: "{{ COMMON_MYSQL_ADMIN_USER.split('@')[0] }}"
    password: "{{ COMMON_MYSQL_ADMIN_PASS }}"
    priv: "*.*:CREATE USER"
